# Generated by Django 5.2.1 on 2025-09-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('warranty_expiry', models.DateField()),
                ('maintenance_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Under Maintenance', 'Under Maintenance'), ('Damaged', 'Damaged')], default='Working', max_length=20)),
            ],
        ),
    ]
